{% set name = "ansible-lint" %}
{% set version = "6.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b539bc22d13e6de0cc2e25758e1d28b2bc01561a414ae37ceda3708b5a2a79ed

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - ansible-lint = ansiblelint.__main__:main
  skip: true  # [win or py < 36]
requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python
    - enrich >=1.2.6
    - packaging
    - pyyaml
    - rich >=9.5.1
    - ruamel.yaml >=0.15.37,<1
    - tenacity
    - typing-extensions  # [py < 38]
    - wcmatch >=7.0
    - yamllint >=1.25.0

test:
  imports:
    - ansiblelint

about:
  home: https://github.com/ansible/ansible-lint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Checks playbooks for practices and behaviour that could potentially be improved
  description: |
    Ansible Lint is a commandline tool for linting playbooks. Use it to detect behaviors and practices that could potentially be improved.
    The tool is used by the Ansible Galaxy project to lint and calculate quality scores for content contributed to the Galaxy Hub.
    The project was originally started by @willthames, and has since been transferred to the Ansible project team.
  doc_url: https://docs.ansible.com/ansible-lint/
  dev_url: https://github.com/ansible/ansible-lint

extra:
  recipe-maintainers:
    - knightdave
    - tschoonj
