{% set name = "ansible-lint" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 093c37ca9a811f08eb14ef93fdf44af1fbb33cc9af7a37352ec491f4c598054a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - ansible-lint = ansiblelint.__main__:main
requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
    - ansible >=2.8
    - ruamel.yaml
  run:
    - python >=3.6
    - ansible >=2.8
    - six
    - ruamel.yaml

test:
  imports:
    - ansiblelint

about:
  home: https://github.com/ansible/ansible-lint
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Checks playbooks for practices and behaviour that could potentially be improved
  description: |
    Ansible Lint is a commandline tool for linting playbooks. Use it to detect behaviors and practices that could potentially be improved.
    The tool is used by the Ansible Galaxy project to lint and calculate quality scores for content contributed to the Galaxy Hub.
    The project was originally started by @willthames, and has since been transferred to the Ansible project team.
  doc_url: https://docs.ansible.com/ansible-lint/
  dev_url: https://github.com/ansible/ansible-lint

extra:
  recipe-maintainers:
    - knightdave
