{% set name = "ansible-lint" %}
{% set version = "6.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 804dc715436cde6a74f44e808445c2f11d7efd016541b27bb6ec58cfdb1b1f6d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - ansible-lint = ansiblelint.__main__:main
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.8
    - ansible-compat >=2.2.0
    - ansible-core >=2.12.0
    - black >=22.1.0
    - enrich >=1.2.6
    - filelock
    - jsonschema >=4.9.0
    - packaging
    - pyyaml
    - rich >=9.5.1
    - ruamel.yaml >=0.15.34,<0.18
    - wcmatch >=7.0
    - yamllint >=1.25.0

test:
  imports:
    - ansiblelint

about:
  home: https://github.com/ansible/ansible-lint
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Checks playbooks for practices and behaviour that could potentially be improved
  description: |
    Ansible Lint is a commandline tool for linting playbooks. Use it to detect behaviors and practices that could potentially be improved.
    The tool is used by the Ansible Galaxy project to lint and calculate quality scores for content contributed to the Galaxy Hub.
    The project was originally started by @willthames, and has since been transferred to the Ansible project team.
  doc_url: https://docs.ansible.com/ansible-lint/
  dev_url: https://github.com/ansible/ansible-lint

extra:
  recipe-maintainers:
    - knightdave
    - tschoonj
