{% set name = "ansible-lint" %}
{% set version = "24.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6bc5d6273f33711ec6d370dfe5fdbe97a64b4c36c2a7a19a249401326eb03616

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - ansible-lint = ansiblelint.__main__:main
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - python >=3.9
    - ansible-core >=2.12.0
    - ansible-compat >=4.0.5
    - black >=22.8.0
    - filelock >=3.3.0
    - jsonschema >=4.10.0
    - packaging >=21.3
    - pathspec >=0.10.3
    - pyyaml >=5.4.1
    - requests >=2.31.0
    - rich >=12.0.0
    - ruamel.yaml >=0.18.5
    - subprocess-tee >=0.4.1
    - yamllint >=1.30.0
    - wcmatch >=8.1.2

test:
  imports:
    - ansiblelint
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ansible/ansible-lint
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Checks playbooks for practices and behaviour that could potentially be improved
  description: |
    Ansible Lint is a commandline tool for linting playbooks. Use it to detect behaviors and practices that could potentially be improved.
    The tool is used by the Ansible Galaxy project to lint and calculate quality scores for content contributed to the Galaxy Hub.
    The project was originally started by @willthames, and has since been transferred to the Ansible project team.
  doc_url: https://docs.ansible.com/ansible-lint/
  dev_url: https://github.com/ansible/ansible-lint

extra:
  recipe-maintainers:
    - knightdave
    - tschoonj
